### ISSUE TITLE
IllegalStateException when opening playlist

### ISSUE THREAD

**Issue by LukeOwncloud** [clementine-player/Android-Remote#111]
At one point Android-Remote crashed. Now very often when  I start it and try to connected it crashes again (cf. https://github.com/clementine-player/Android-Remote/issues/110). If it does not crashes immediately, it crashes when I open the playlist.

This is the error report:

== Device Information ==

OS Version: 4.2.2 (3.4.0-perf-g7ce11cd)
OS API Level: 17
Device: mako
Model (and Product): Nexus 4 (occam)
App Version: v10.1 (479)

Max memory: 536870912
Current heap: 23896064
Heap available: 1993264
Native Heap: 6174168

== Stacktrace ==

java.lang.IllegalStateException: setSelectedNavigationIndex not valid for current navigation mode
at com.android.internal.app.ActionBarImpl.setSelectedNavigationItem(ActionBarImpl.java:362)
at de.qspool.clementineremote.ui.fragments.PlaylistFragment.getSelectedPlaylistPosition(PlaylistFragment.java:525)
at de.qspool.clementineremote.ui.fragments.PlaylistFragment.getSelectedPlaylistSongs(PlaylistFragment.java:518)
at de.qspool.clementineremote.ui.fragments.PlaylistFragment.updateSongList(PlaylistFragment.java:374)
at de.qspool.clementineremote.ui.fragments.PlaylistFragment.MessageFromClementine(PlaylistFragment.java:457)
at de.qspool.clementineremote.ui.MainActivity.MessageFromClementine(MainActivity.java:387)
at de.qspool.clementineremote.ui.MainActivityHandler.handleMessage(MainActivityHandler.java:63)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)

**Comment by amuttsch** [comment]
Please try the newest version. I changed the behavior so it should be fixed.

**Comment by LukeOwncloud** [comment]
Could not reproduce with version 10.1-102.
