### ISSUE TITLE
Crash when goin into background

### ISSUE THREAD

**Issue by 6543** [clementine-player/Android-Remote#211]
```log
== User Information ==
If you have any further information what you did to cause the crash or how to reproduce it, please write it here.


== Device Information ==

OS Version: 10 (4.4.205-perf+)
OS API Level: 29
Device: OnePlus5T
Model (and Product): ONEPLUS A5010 (OnePlus5T)
App Version: v12 (759)

Max memory: 536870912
Current heap: 14138040
Heap available: 3451968
Native Heap: 26200984

== Stacktrace ==

java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.qspool.clementineremote/.backend.ClementineService (has extras) }: app is in background uid UidRecord{4fdb863 u0a150 SVC  bg:+1m6s746ms idle change:idle procs:1 seq(0,0,0)}
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1650)
 at android.app.ContextImpl.startService(ContextImpl.java:1605)
 at android.content.ContextWrapper.startService(ContextWrapper.java:669)
 at de.qspool.clementineremote.backend.ClementineService.sendDisconnectServiceMessage(ClementineService.java:213)
 at de.qspool.clementineremote.backend.ClementineService.access$100(ClementineService.java:51)
 at de.qspool.clementineremote.backend.ClementineService$1.onConnectionStatusChanged(ClementineService.java:157)
 at de.qspool.clementineremote.backend.ClementinePlayerConnection.fireOnConnectionStatusChanged(ClementinePlayerConnection.java:313)
 at de.qspool.clementineremote.backend.ClementinePlayerConnection.closeConnection(ClementinePlayerConnection.java:272)
 at de.qspool.clementineremote.backend.ClementinePlayerConnection.disconnect(ClementinePlayerConnection.java:245)
 at de.qspool.clementineremote.backend.ClementineConnectionHandler.handleMessage(ClementineConnectionHandler.java:57)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at de.qspool.clementineremote.backend.ClementinePlayerConnection.run(ClementinePlayerConnection.java:89)
 at java.lang.Thread.run(Thread.java:919)
```

**Comment by quamok** [comment]
Same here!

== User Information ==
If you have any further information what you did to cause the crash or how to reproduce it, please write it here.


== Device Information ==

OS Version: 11 (4.14.199)
OS API Level: 30
Device: coral
Model (and Product): Pixel 4 XL (calyx_coral)
App Version: v12 (759)

Max memory: 536870912
Current heap: 11275208
Heap available: 8219856
Native Heap: 18114960

== Stacktrace ==

java.lang.IllegalStateException: Not allowed to start service Intent { cmp=de.qspool.clementineremote/.backend.ClementineService (has extras) }: app is in background uid UidRecord{d0e60b7 u0a120 TPSL bg:+2m30s733ms idle change:cached procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
at android.app.ContextImpl.startService(ContextImpl.java:1670)
at android.content.ContextWrapper.startService(ContextWrapper.java:720)
at de.qspool.clementineremote.backend.ClementineService.sendDisconnectServiceMessage(ClementineService.java:213)
at de.qspool.clementineremote.backend.ClementineService.access$100(ClementineService.java:51)
at de.qspool.clementineremote.backend.ClementineService$1.onConnectionStatusChanged(ClementineService.java:157)
at de.qspool.clementineremote.backend.ClementinePlayerConnection.fireOnConnectionStatusChanged(ClementinePlayerConnection.java:313)
at de.qspool.clementineremote.backend.ClementinePlayerConnection.closeConnection(ClementinePlayerConnection.java:272)
at de.qspool.clementineremote.backend.ClementinePlayerConnection.disconnect(ClementinePlayerConnection.java:245)
at de.qspool.clementineremote.backend.ClementineConnectionHandler.handleMessage(ClementineConnectionHandler.java:57)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at de.qspool.clementineremote.backend.ClementinePlayerConnection.run(ClementinePlayerConnection.java:89)
at java.lang.Thread.run(Thread.java:923)

**Comment by 6543** [comment]
looks like an Android-API issue: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten#47654126 ?
